#!/bin/bash
set -euo pipefail
echo "Full worker-user-data.sh is generated by TerraPilot and runs this worker flow automatically."
echo "Waiting for the kubeadm join command in SSM Parameter Store."
for i in {1..120}; do
  JOIN_COMMAND=$(aws ssm get-parameter --name "$TERRAPILOT_SSM_JOIN_PRIVATE_PATH" --with-decryption --query "Parameter.Value" --output text --region "$AWS_REGION" 2>/dev/null || true)
  if [ -n "$JOIN_COMMAND" ] && echo "$JOIN_COMMAND" | grep -q "kubeadm join"; then
    bash -c "$JOIN_COMMAND"
    exit 0
  fi
  sleep 10
done
echo "Timed out waiting for SSM worker join command."
exit 1
