apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: stateful-app
type: Opaque
stringData:
  POSTGRES_DB: "kubestate"
  POSTGRES_USER: "kubestate"
  POSTGRES_PASSWORD: "Kb$9xLm2#pQr7wNz"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: stateful-app
type: Opaque
stringData:
  DATABASE_URL: "postgresql://kubestate:Kb$9xLm2#pQr7wNz@postgres.stateful-app.svc.cluster.local:5432/kubestate"
