apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: stateful-app
type: Opaque
stringData:
  POSTGRES_DB: "kubestate"
  POSTGRES_USER: "kubestate"
  POSTGRES_PASSWORD: "REPLACE_WITH_STRONG_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: stateful-app
type: Opaque
stringData:
  DATABASE_URL: "postgresql://kubestate:REPLACE_WITH_STRONG_PASSWORD@postgres.stateful-app.svc.cluster.local:5432/kubestate"
