apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: stateful-app
type: Opaque
stringData:
  DATABASE_URL: "postgresql://kubestate:REPLACE_WITH_PASSWORD@postgres.stateful-app.svc.cluster.local:5432/kubestate"
  REDIS_URL: "redis://redis.stateful-app.svc.cluster.local:6379/0"
  SECRET_KEY: "REPLACE_WITH_STRONG_SECRET"
