apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config
  namespace: stateful-app
data:
  APP_ENV: "dev"
  POSTGRES_HOST: "postgres.stateful-app.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "kubestate"
  REDIS_HOST: "redis.stateful-app.svc.cluster.local"
  REDIS_PORT: "6379"
  S3_BACKUP_PREFIX: "postgres-backups"
