apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: stateful-app
type: Opaque
stringData:
  POSTGRES_DB: "kubestate"
  POSTGRES_USER: "kubestate"
  POSTGRES_PASSWORD: "REPLACE_WITH_PASSWORD"
